on:
  push:
    branches: [ master ]
    paths-ignore: [ '**.md' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Restore workloads
        run: dotnet workload restore
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false
          
      - name: Build
        run: dotnet build KalugaBus/KalugaBus.csproj -p:TargetFrameworks=net8.0-android
        
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
          
      - name: Restore workloads
        run: dotnet workload restore

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false
          
      - name: Getting keystore
        id: get_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'KalugaBus.keystore'
          encodedString: ${{ secrets.KEYSTORE_ENCODED }}
      
      - name: Publish
        run: dotnet publish KalugaBus/KalugaBus.csproj -p:TargetFrameworks=net8.0-android -f net8.0-android -c Release -p:AndroidKeyStore=true -p:AndroidSigningKeyStore=${{ steps.get_keystore.outputs.filePath }} -p:AndroidSigningKeyAlias=kalugabus -p:AndroidSigningKeyPass=${{ secrets.KEYSTORE_PASS }} -p:AndroidSigningStorePass=${{ secrets.KEYSTORE_PASS }}
        
      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: com.danimatcorp.kalugabus.apk
          path: KalugaBus/bin/Release/net8.0-android/publish/com.danimatcorp.kalugabus-Signed.apk
          
      - name: Archive AAB
        uses: actions/upload-artifact@v4
        with:
          name: com.danimatcorp.kalugabus.aab
          path: KalugaBus/bin/Release/net8.0-android/publish/com.danimatcorp.kalugabus-Signed.aab